services:
  database:
    build:
      context: database
    env_file:
      - .env
      - .env.local
    ports:
      - "127.0.0.1:${DATABASE_HOST_PORT:?DATABASE_HOST_PORT is required}:5432"
    volumes:
      - local_database_data:/var/lib/postgresql
volumes:
  local_database_data:
