"""
Ensures that no text file of the repository carries merge conflict markers written into its content.

A textual conflict is detected by the repository hosting, which blocks the Merge Request on its own, but a marker
resolved badly and merged as regular content passes on unnoticed. `ruff` catches it only in Python code and only outside
a string literal - in a docstring the marker is valid content. Markdown, YAML, compose files, `makefile`
and SQL have no reader today that would see it. A marker in `makefile` is enough to make no
`make` target runnable.

The test scans every text file, Python included, and not only the ones `ruff` does not read - because of
the docstrings above. It treats a file containing a null byte as binary and skips it, because a marker in it
is not content anybody merges by hand. The scan works on bytes, without decoding, so a file
in an encoding other than UTF-8 does not abort the test.

Local configuration files are part of the scan, because a marker in them breaks the environment just the same, but a report
gives only the path, the line number and the marker kind - never the content of the line.

Three markers are recognized: the opening one (seven less-than signs), the closing one (seven
greater-than signs) and the diff3-style common ancestor marker (seven vertical bars), each at the beginning of a line
and terminated by a space or the end of the line. The separator of seven equals signs is deliberately not
recognized: such a line is also a valid heading underline in markdown, and a conflict leaving
only the separator without both surrounding markers does not arise in any resolution that starts
from the content generated by git.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]

EXCLUDED_DIRECTORY_NAMES: frozenset[str] = frozenset({".venv", "venv", ".git", ".cache", "__pycache__", "build", "dist", "node_modules", "temp", ".context"})
EXCLUDED_DIRECTORY_PREFIXES: tuple[str, ...] = ("pytest_tmp",)
"""
Repeats the directory exclusions from `test_prose_style.py` and adds `.context`, so that both repository scans
agree on what is repository content and what is an artifact of the environment or a tool.
"""

MARKER_LENGTH = 7

CONFLICT_MARKER_PATTERN = re.compile(rb"^(?P<marker><{7}|>{7}|\|{7})(?: [^\n]*)?\r?$", re.MULTILINE)
"""
A line starting with one of the three git markers, followed by a space with a label or the end of the
line. An eighth character of the same kind is not a marker, so a line with eight greater-than signs, for
example a nested quote, is not reported.
"""

MARKER_KINDS: dict[bytes, str] = {b"<" * MARKER_LENGTH: "opening", b">" * MARKER_LENGTH: "closing", b"|" * MARKER_LENGTH: "common ancestor"}

BINARY_FILE_SIGNATURE = b"\x00"


@dataclass(frozen=True)
class ConflictMarkerViolation:
    """
    One occurrence of a conflict marker: the file, the line and the marker kind, without the content of the line.
    """

    path: str
    line_number: int
    marker_kind: str

    @property
    def report_line(self) -> str:
        """
        Builds one report line pointing out where the marker stands and what kind it is.
        """
        return f"  {self.path}:{self.line_number} - {self.marker_kind} marker"


def fetch_scanned_files(root: Path) -> list[Path]:
    """
    Returns a sorted list of all files under `root`, skipping the tool directories
    excluded the same way as in the prose style scan.
    """
    scanned_files: list[Path] = []

    for directory, directory_names, file_names in root.walk(on_error=lambda _: None):
        directory_names[:] = [name for name in directory_names if name not in EXCLUDED_DIRECTORY_NAMES and not name.startswith(EXCLUDED_DIRECTORY_PREFIXES)]
        scanned_files.extend(directory / name for name in file_names)

    return sorted(scanned_files)


def resolve_conflict_marker_violations(path: str, content: bytes) -> list[ConflictMarkerViolation]:
    """
    Points out every conflict marker in the content of one file. A binary file produces no report.
    """
    if BINARY_FILE_SIGNATURE in content:
        return []

    violations: list[ConflictMarkerViolation] = []

    for match in CONFLICT_MARKER_PATTERN.finditer(content):
        line_number = content.count(b"\n", 0, match.start()) + 1
        violations.append(ConflictMarkerViolation(path=path, line_number=line_number, marker_kind=MARKER_KINDS[match.group("marker")]))

    return violations


def fetch_repository_violations(root: Path) -> list[ConflictMarkerViolation]:
    """
    Scans the whole repository and collects all conflict markers from all text files.
    """
    violations: list[ConflictMarkerViolation] = []

    for file_path in fetch_scanned_files(root):
        try:
            content = file_path.read_bytes()
        except OSError:
            continue

        violations.extend(resolve_conflict_marker_violations(file_path.relative_to(root).as_posix(), content))

    return violations


def build_violation_report(violations: Sequence[ConflictMarkerViolation]) -> str:
    """
    Builds the failed test message: a header and one line for every marker found.
    """
    return "\n".join(["Merge conflict markers in file content - resolve the conflict completely:", *(violation.report_line for violation in violations)])


def build_marker_line(marker: bytes, label: bytes = b"") -> bytes:
    """
    Builds a marker line with an optional label, the way git writes it.
    """
    return marker + (b" " + label if label else b"")


def test_repository_has_no_conflict_markers() -> None:
    """
    Ensures that no text file of the repository contains a conflict marker at the beginning of a line.
    """
    violations = fetch_repository_violations(ROOT_DIR)

    assert not violations, build_violation_report(violations)


def test_resolve_conflict_marker_violations_reports_each_marker_with_its_line() -> None:
    """
    Ensures that a full diff3-style conflict block produces three reports with the correct line numbers and kinds.
    """
    content = b"\n".join(
        [
            b"title",
            build_marker_line(b"<" * MARKER_LENGTH, b"HEAD"),
            b"our version",
            build_marker_line(b"|" * MARKER_LENGTH, b"merged common ancestors"),
            b"ancestor version",
            b"=" * MARKER_LENGTH,
            b"their version",
            build_marker_line(b">" * MARKER_LENGTH, b"origin/dev"),
            b"",
        ]
    )

    violations = resolve_conflict_marker_violations("file.md", content)

    assert [(violation.line_number, violation.marker_kind) for violation in violations] == [(2, "opening"), (4, "common ancestor"), (8, "closing")]


def test_resolve_conflict_marker_violations_flags_marker_without_label_and_with_crlf() -> None:
    """
    Ensures that a marker without a label and a marker terminated by a Windows line ending are reported the same way.
    """
    content = b"\r\n".join([b"a", b"<" * MARKER_LENGTH, b"b", build_marker_line(b">" * MARKER_LENGTH, b"feature"), b""])

    violations = resolve_conflict_marker_violations("compose.yaml", content)

    assert [violation.line_number for violation in violations] == [2, 4]


def test_resolve_conflict_marker_violations_ignores_setext_underline() -> None:
    """
    Ensures that a markdown heading underline of seven equals signs is not reported.
    """
    content = b"Heading\n" + b"=" * MARKER_LENGTH + b"\n\ncontent\n"

    assert resolve_conflict_marker_violations("file.md", content) == []


def test_resolve_conflict_marker_violations_ignores_marker_not_starting_the_line() -> None:
    """
    Ensures that a marker quoted in the middle of a line, for example in documentation about conflicts, is not reported.
    """
    content = b"A line with a marker `" + b"<" * MARKER_LENGTH + b"` in a quote.\n"

    assert resolve_conflict_marker_violations("file.md", content) == []


def test_resolve_conflict_marker_violations_ignores_longer_run_of_the_same_character() -> None:
    """
    Ensures that eight greater-than signs at the beginning of a line, that is a nested quote, are not a marker.
    """
    content = b">" * (MARKER_LENGTH + 1) + b" quote\n"

    assert resolve_conflict_marker_violations("file.md", content) == []


def test_resolve_conflict_marker_violations_skips_binary_content() -> None:
    """
    Ensures that a file with a null byte is treated as binary and produces no reports despite a marker in its content.
    """
    content = BINARY_FILE_SIGNATURE + b"\n" + build_marker_line(b"<" * MARKER_LENGTH, b"HEAD") + b"\n"

    assert resolve_conflict_marker_violations("image.png", content) == []


def test_repository_scan_reports_marker_planted_in_a_scanned_file(tmp_path: Path) -> None:
    """
    Ensures that the directory scan finds a marker in a compose file but skips the same marker in an excluded directory.
    """
    marker_line = build_marker_line(b"<" * MARKER_LENGTH, b"HEAD") + b"\n"
    (tmp_path / "compose.yaml").write_bytes(b"services:\n" + marker_line)
    excluded_directory = tmp_path / "node_modules"
    excluded_directory.mkdir()
    (excluded_directory / "README.md").write_bytes(marker_line)

    violations = fetch_repository_violations(tmp_path)

    assert [(violation.path, violation.line_number) for violation in violations] == [("compose.yaml", 2)]
